### PR TITLE
Support Symfony 5.0

### PR DESCRIPTION
**Pull request by vincentchalamon**
This PR adds support for Symfony 5.

### CODE REVIEW

**Comment by Lctrs** [comment]
Hi and thank you for your PR.

Sadly, this lib can't be fully compatible with Symfony 5 as `behat/mink-extension` is not as well. Once they release a version compatible with Symfony 5, I'll drop support for Sf 4 and add support for Sf 5.

**Comment by vincentchalamon** [comment]
Hi @Lctrs,

Thanks for your feedback. I use [friends-of-behat](https://packagist.org/packages/friends-of-behat/) packages which replace some behat packages, including [friends-of-behat/mink-extension](https://packagist.org/packages/friends-of-behat/mink-extension).

As your package requires `behat/mink: v1.8.1` but `friends-of-behat/mink` is only available in v1.8.0, I managed to install it in a Symfony 5 project using my fork and the following syntax:
```
"require-dev": {
    "friends-of-behat/mink": "1.8.0 as 1.8.1",
    "lctrs/mink-panther-driver": "dev-master"
}
```

**Comment by Lctrs** [comment]
So, I replaced `behat/mink-extension` by `friends-of-behat/mink-extension`, upgraded all Symfony components to version 5 in `composer.json`, but on update, composer tells me that `matthiasnoback/symfony-dependency-injection-test` v3.x doesn't support Symfony 5. Version 4.x does, but it supports only `PHPUnit` 8.x, which we can't support because `mink/driver-testsuite` is stuck at `PHPUnit` 7.x.

So, I guess that Symfony 5 support won't happen anytime soon.

**Comment by Lctrs** [comment]
Closing this. Thanks anyway @vincentchalamon !

**Comment by vincentchalamon** [comment]
Thanks for trying :-)

BTW, why do you keep a composer.lock file updated in your library?

**Comment by Lctrs** [comment]
To have a reproducible dev environment.

For example, I don't want that an update to a dependency of `doctrine/coding-standard` breaks the CS check while I'm working on something totally unrelated.

**Pull request closed without merging**
